import { PhysicalTable, SqlDialect } from "../types";

export function generateSqlDdl(tables: PhysicalTable[], dialect: SqlDialect): string {
  if (!tables || tables.length === 0) {
    return "-- No physical tables defined yet.";
  }

  const lines: string[] = [];
  lines.push(`-- =========================================================================`);
  lines.push(`-- SILVER LAKEHOUSE PHYSICAL DDL SCRIPT`);
  lines.push(`-- Target Engine: ${dialect.toUpperCase()}`);
  lines.push(`-- Generated by SilverCraft Assisted Data Modeler`);
  lines.push(`-- Date: ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`-- =========================================================================\n`);

  tables.forEach((tbl) => {
    lines.push(`-- -------------------------------------------------------------------------`);
    lines.push(`-- Table: ${tbl.schema}.${tbl.tableName}`);
    lines.push(`-- Description: ${tbl.comment || "Silver Lakehouse Table"}`);
    lines.push(`-- -------------------------------------------------------------------------`);

    if (dialect === "Databricks Delta") {
      lines.push(`CREATE TABLE IF NOT EXISTS ${tbl.schema}.${tbl.tableName} (`);
      const colDefs = tbl.columns.map((c) => {
        let def = `  ${c.columnName} ${c.dataType}`;
        if (!c.isNullable) def += " NOT NULL";
        if (c.comment) def += ` COMMENT '${c.comment.replace(/'/g, "''")}'`;
        return def;
      });
      lines.push(colDefs.join(",\n"));
      lines.push(`) USING DELTA`);

      const partKeys = tbl.columns.filter((c) => c.isPartitionKey).map((c) => c.columnName);
      if (partKeys.length > 0) {
        lines.push(`PARTITIONED BY (${partKeys.join(", ")})`);
      }
      lines.push(`COMMENT '${tbl.comment.replace(/'/g, "''")}';\n`);
    } else if (dialect === "Snowflake") {
      lines.push(`CREATE TABLE IF NOT EXISTS ${tbl.schema}.${tbl.tableName} (`);
      const colDefs = tbl.columns.map((c) => {
        let def = `  ${c.columnName} ${c.dataType}`;
        if (!c.isNullable) def += " NOT NULL";
        if (c.comment) def += ` COMMENT '${c.comment.replace(/'/g, "''")}'`;
        return def;
      });

      const pkCols = tbl.columns.filter((c) => c.isPrimaryKey).map((c) => c.columnName);
      if (pkCols.length > 0) {
        colDefs.push(`  CONSTRAINT pk_${tbl.tableName} PRIMARY KEY (${pkCols.join(", ")})`);
      }

      lines.push(colDefs.join(",\n"));
      lines.push(`)`);

      const clusterKeys = tbl.columns.filter((c) => c.isClusteringKey).map((c) => c.columnName);
      if (clusterKeys.length > 0) {
        lines.push(`CLUSTER BY (${clusterKeys.join(", ")})`);
      }
      lines.push(`COMMENT = '${tbl.comment.replace(/'/g, "''")}';\n`);
    } else if (dialect === "BigQuery") {
      lines.push(`CREATE TABLE IF NOT EXISTS \`${tbl.schema}.${tbl.tableName}\` (`);
      const colDefs = tbl.columns.map((c) => {
        let def = `  \`${c.columnName}\` ${c.dataType}`;
        if (!c.isNullable) def += " NOT NULL";
        if (c.comment) def += ` OPTIONS(description="${c.comment.replace(/"/g, '\\"')}")`;
        return def;
      });
      lines.push(colDefs.join(",\n"));
      lines.push(`)`);

      const partKeys = tbl.columns.filter((c) => c.isPartitionKey).map((c) => c.columnName);
      if (partKeys.length > 0) {
        lines.push(`PARTITION BY ${partKeys[0]}`);
      }

      const clusterKeys = tbl.columns.filter((c) => c.isClusteringKey).map((c) => c.columnName);
      if (clusterKeys.length > 0) {
        lines.push(`CLUSTER BY ${clusterKeys.join(", ")}`);
      }
      lines.push(`OPTIONS(description="${tbl.comment.replace(/"/g, '\\"')}");\n`);
    } else {
      // PostgreSQL / Standard SQL
      lines.push(`CREATE TABLE IF NOT EXISTS ${tbl.schema}.${tbl.tableName} (`);
      const colDefs = tbl.columns.map((c) => {
        let def = `  ${c.columnName} ${c.dataType}`;
        if (c.isPrimaryKey) def += " PRIMARY KEY";
        else if (!c.isNullable) def += " NOT NULL";
        return def;
      });
      lines.push(colDefs.join(",\n"));
      lines.push(`);\n`);
    }
  });

  return lines.join("\n");
}
